# What the credentials.yml should look like
spring:
    mail:
        username: your mail
        password: your password
        properties:
            mail.smtp.starttls.enable: true
            mail.smtp.auth: true
